import {products,settings} from './data.js';
const $=s=>document.querySelector(s),money=c=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(c/100),byId=new Map(products.map(p=>[p.id,p])),key='bridging-craft-cart-v1';
const clean=v=>Object.fromEntries(Object.entries(v&&typeof v==='object'?v:{}).filter(([id,q])=>byId.has(id)&&Number.isInteger(q)&&q>0&&q<=99));
let cart={},timer;
try{cart=clean(JSON.parse(localStorage.getItem(key)||'{}'));}catch{}
const params=new URLSearchParams(location.search);
if(params.has('items')){cart={};for(const part of params.get('items').split(',')){const [id,q,...rest]=part.split(':');if(!rest.length&&/^\d+$/.test(q)&&byId.has(id)&&Number(q)>0&&Number(q)<=99)cart[id]=Number(q);}}
function cartURL(){const url=new URL(location.pathname,location.origin);url.searchParams.set('view','cart');url.searchParams.set('items',Object.entries(cart).map(([id,q])=>`${id}:${q}`).join(','));return url.href;}
function notify(text){$('#notice').textContent=text;clearTimeout(timer);timer=setTimeout(()=>$('#notice').textContent='',4000);}
function save(){try{localStorage.setItem(key,JSON.stringify(cart));}catch{notify('Copy the selection link to save it; browser storage is unavailable.');}$('#cart-count').textContent=Object.values(cart).reduce((a,b)=>a+b,0);$('#cart-link').href=cartURL();}
function update(id,q){if(!byId.has(id))return;if(!Number.isInteger(q)||q<0||q>99){notify('Choose a quantity from 1 to 99.');return;}if(q===0)delete cart[id];else cart[id]=q;save();if(params.get('view')==='cart'){history.replaceState(null,'',cartURL());renderCart();}}
function renderProducts(){const term=$('#search').value.trim().toLowerCase(),category=$('#category').value,min=$('#min-price').value,max=$('#max-price').value;let list=products.filter(p=>(p.name+' '+p.description).toLowerCase().includes(term)&&(!category||p.category===category)&&(min===''||p.usdCents>=Math.round(Number(min)*100))&&(max===''||p.usdCents<=Math.round(Number(max)*100)));const sort=$('#sort').value;list.sort((a,b)=>sort==='price-low'?a.usdCents-b.usdCents:sort==='price-high'?b.usdCents-a.usdCents:b.addedAt.localeCompare(a.addedAt)||a.id.localeCompare(b.id));$('#products').innerHTML=list.map(p=>`<article class="product-card"><button class="image-button" data-detail="${p.id}" aria-label="View ${p.name}"><img src="images/${p.image}" alt="${p.name}" loading="lazy"></button><p class="product-meta">${p.category} · ${p.id}</p><h2><button class="title-button" data-detail="${p.id}">${p.name}</button></h2><div class="price-row"><p class="price">${money(p.usdCents)} <span class="muted">USD</span></p><button class="add" data-add="${p.id}">Add to selection</button></div></article>`).join('')||'<p class="empty">No pieces match. Try another search or clear the filters.</p>';$('#result-count').textContent=`${list.length} pieces · Estimated USD prices`;}
function detail(id){const p=byId.get(id);if(!p)return;$('#detail-content').innerHTML=`<div class="detail-grid"><img src="images/${p.image}" alt="${p.name}"><div><p class="eyebrow">${p.category} · ${p.id}</p><h2>${p.name}</h2><p>${p.description}</p><dl><dt>Maker</dt><dd>${p.supplier}</dd><dt>Origin</dt><dd>${p.location}</dd><dt>Dimensions</dt><dd>${p.dimensions}</dd><dt>Material</dt><dd>${p.material}</dd><dt>Added to catalog</dt><dd>${p.addedAt}</dd><dt>Original price</dt><dd>${p.cop.toLocaleString('en-US')} COP</dd></dl><p class="price">${money(p.usdCents)} USD <span class="muted">estimated</span></p><button class="primary" data-add="${p.id}">Add to selection</button><p class="muted">Availability and final specifications require confirmation.</p></div></div>`;$('#detail').showModal();}
const icon='<svg class="whatsapp-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2a10 10 0 0 0-8.7 15L2 22l5.2-1.3A10 10 0 1 0 12 2Zm0 18a8 8 0 0 1-4.1-1.1l-.4-.2-3 .8.8-2.9-.3-.4A8 8 0 1 1 12 20Zm4.5-5.9c-.3-.1-1.6-.8-1.8-.9-.3-.1-.4-.1-.6.2l-.8.9c-.1.2-.3.2-.5.1-1.3-.6-2.5-1.6-3.1-2.8-.2-.3.2-.5.5-.9.1-.2.1-.3 0-.5L9.4 8c-.2-.4-.4-.4-.6-.4h-.5c-.2 0-.5.1-.7.3-.7.7-.8 1.7-.5 2.6.7 2.1 2.3 3.9 4.3 5 1.5.8 3.1 1.3 4.2.3.4-.4.6-1.2.5-1.4 0-.1-.2-.2-.5-.3Z"/></svg>';
function renderCart(){const entries=Object.entries(cart),total=entries.reduce((s,[id,q])=>s+byId.get(id).usdCents*q,0),phone=settings.businessPhone.replace(/\D/g,''),ready=/^[1-9]\d{7,14}$/.test(phone);$('#cart-view').innerHTML=`<a class="back" href="?">← Back to the collection</a><p class="eyebrow">Your collection, considered</p><h1>Your selection.</h1>${entries.length?`<div class="cart-layout"><div>${entries.map(([id,q])=>{const p=byId.get(id);return `<article class="cart-item"><img src="images/${p.image}" alt="${p.name}"><div><h2><button class="title-button" data-detail="${id}">${p.name}</button></h2><p>${id} · ${money(p.usdCents)} USD each</p><div class="quantity"><button data-quantity="${id}" data-step="-1" aria-label="Decrease ${p.name}">−</button><input type="number" min="1" max="99" step="1" value="${q}" data-input="${id}" aria-label="Quantity of ${p.name}"><button data-quantity="${id}" data-step="1" aria-label="Increase ${p.name}">+</button><button class="quiet" style="width:auto;border:0" data-remove="${id}">Remove</button></div></div><strong>${money(p.usdCents*q)}</strong></article>`;}).join('')}</div><aside class="summary"><div class="total"><span>Estimated total</span><strong>${money(total)}</strong></div><p class="muted">USD · Delivery and applicable taxes are not included. Availability and final pricing require confirmation.</p>${ready?`<a id="place-order" class="primary" target="_blank" rel="noopener">${icon} Place Order</a>`:`<button class="primary" disabled>${icon} Place Order</button><p class="warning">WhatsApp ordering will be available once the business number is added: ${settings.phonePlaceholder}.</p>`}<button class="secondary" id="download">Download selection as Excel</button><div class="share-box"><label>Shareable selection link<input id="share-url" readonly></label><button id="copy" class="quiet">Copy link</button></div><p class="muted">This link shares product IDs and quantities only. No payment is collected here.</p></aside></div>`:'<p class="empty">Your selection is empty. Explore the collection to add a piece.</p>'}`;if(entries.length){$('#share-url').value=cartURL();if(ready)$('#place-order').href=`https://wa.me/${phone}?text=${encodeURIComponent('Hello Catalina, please confirm availability and final pricing for this Bridging Craft selection. Estimated total: '+money(total)+' USD. '+cartURL())}`;}}
async function download(){const button=$('#download');button.disabled=true;try{const book=new ExcelJS.Workbook();book.creator='Bridging Craft';const sheet=book.addWorksheet('Order selection');sheet.columns=[{width:19},{width:44},{width:12},{width:19},{width:20}];sheet.addRow(['Bridging Craft — Order selection']);sheet.addRow(['Estimated USD prices; final pricing requires confirmation.']);sheet.addRow(['Product ID','Product','Quantity','Unit price (USD)','Subtotal (USD)']);let total=0;Object.entries(cart).forEach(([id,q])=>{const p=byId.get(id),r=sheet.rowCount+1;total+=p.usdCents*q;sheet.addRow([id,p.name,q,p.usdCents/100,{formula:`C${r}*D${r}`,result:p.usdCents*q/100}]);});const end=sheet.rowCount;sheet.addRow(['','TOTAL (USD)','','',{formula:`SUM(E4:E${end})`,result:total/100}]);sheet.addRow([]);sheet.addRow(['Exchange rate',`1 USD = ${settings.copPerUsd} COP (${settings.rateDate})`]);sheet.addRow(['Rate source',settings.rateSource]);sheet.addRow(['Selection link',cartURL()]);sheet.addRow(['Note','Delivery and applicable taxes are not included.']);for(const n of [1,3,end+1]){sheet.getRow(n).font={bold:true,color:{argb:'FFF3F0E9'}};sheet.getRow(n).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF502419'}};sheet.getRow(n).height=27;}for(let r=4;r<=end+1;r++){sheet.getCell(`D${r}`).numFmt='"$"#,##0.00';sheet.getCell(`E${r}`).numFmt='"$"#,##0.00';}sheet.views=[{state:'frozen',ySplit:3}];sheet.autoFilter=`A3:E${end}`;const blob=new Blob([await book.xlsx.writeBuffer()],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Bridging-Craft-selection.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('Your Excel selection is ready.');}catch{notify('Excel export could not be created. Please reload and try again.');}finally{button.disabled=false;}}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.detail)detail(b.dataset.detail);if(b.dataset.add){const id=b.dataset.add;if((cart[id]||0)<99){update(id,(cart[id]||0)+1);notify(`${byId.get(id).name} added.`);}else notify('Maximum quantity is 99.');}if(b.dataset.remove)update(b.dataset.remove,0);if(b.dataset.quantity)update(b.dataset.quantity,cart[b.dataset.quantity]+Number(b.dataset.step));if(b.id==='copy'){try{await navigator.clipboard.writeText(cartURL());notify('Selection link copied.');}catch{$('#share-url').select();notify('Select and copy the link shown above.');}}if(b.id==='download')download();});
document.addEventListener('change',e=>{if(e.target.dataset.input){update(e.target.dataset.input,Number(e.target.value));renderCart();}});
$('#close-detail').onclick=()=>$('#detail').close();$('#filters').addEventListener('submit',e=>e.preventDefault());$('#filters').addEventListener('input',renderProducts);$('#reset').onclick=()=>{$('#filters').reset();renderProducts();};save();renderProducts();if(params.get('view')==='cart'){$('#catalog').hidden=true;$('#cart-view').hidden=false;renderCart();}
